### ISSUE TITLE
How to re-zero the Balance board readings?

### ISSUE THREAD

**Issue by qwertychouskie** [wiiuse/wiiuse#104]
I'm trying to get the center of gravity of an object, but when there's nothing on the board `wiiuseexample` reports a non-zero value for one of the corners:
```
Weight: 1.486766 kg @ (1.000000, -1.000000)
Interpolated weight: TL:0.000000  TR:0.000000  BL:0.000000  BR:1.486766
Raw: TL:8300  TR:2779  BL:7056  BR:4163
```
And the others corners don't report anything when a tiny load is applied, only with more weight it starts to register.

How do I re-zero the scale?  I'm happy to change and re-compile the example app if needed.

**Comment by janoc** [comment]
Hello, 

I am not sure you can zero it out. That value is pretty much within the manufacturing tolerance of the device, I believe. Neither the sensors nor the amplifiers they are connected to are ideal devices, there will always be offsets and noise.  On your board it seems the right side (both the TR and BR sensors) is more "heavy" than the left side, giving rise to this. 

This type of offset could be likely compensated by using the calibration data stored in the board's EEPROM but nobody has reverse engineered/implemented this part yet. You are welcome to contribute, the balance board is not all that well supported because few people have one. 

If the offset bothers you, you can also compensate for it in your code by subtracting it out and doing the weight interpolation yourself (the calculation in wiiboard.c is an example of how to do it).

**Comment by DanhuaZhang** [comment]
Hi, I have the question for the center of pressure data: How to calibrate the axis values? Why the default is (1, -1) rather than (0, 0)? What does the axis look like? (the origin and the direction the two axes are pointing to)

**Comment by janoc** [comment]
Please, don't ask questions on unrelated issues, open a new issue instead. See my reply on #108
