### ISSUE TITLE
does the pairing work?

### ISSUE THREAD

**Issue by gb2111** [wiiuse/wiiuse#110]
i was running test app but could not pair or connect to a device. had to use other emulator and then it worked.
can u help?

**Comment by janoc** [comment]
You are not supposed to pair with the Wiimote - it isn't even possible unless your BT stack has specific support for a Wiimote (e.g. Bluez in Linux or BlueSoleil for Windows) because the pairing codes are non-standard (reversed MAC address of the Wiimote in binary, not possible to enter manually). 

You put the Wiimote in discoverable mode (press 1+2 buttons or the red button in the battery compartment, on newer Wiimotes only the red button works) and let Wiiuse find the controller. 

One exception in Windows, there you need to connect to the Wiimote beforehand using the OS tools, as if you were connecting to a gamepad. Then launch Wiiuse and it will find it.

**Comment by gb2111** [comment]
thanks for reply.
i am on windows platform. i can pair wii remote via bluetooth via join personal area network.
then I launch wiiuseexample and it is not detected. but when I first detect it via other software like dolphin and wiiuseexample after that, it will work.

regard.s

**Comment by janoc** [comment]
Yes but Wiiuse does not support pairing. I believe it is even in the README. You need to only connect to the wiimote (not pair it!), then it will work. Dolphin may support pairing now but they are running their own fork of Wiiuse and not contributing the code back, so we don't have it. 

Also you are really skimpy on information - what is "Windows platform"? Windows 10? Windows 7? Windows 8? Windows XP? Are you using the original Microsoft's stack? Third party stack that came with your bluetooth dongle? Without that information it is really difficult to help you.

**Comment by gb2111** [comment]
hi. i am on windows 10. i said i paired wii remote via bluetooth via 'Join Personal Area Network".
so pairing is done. 

but wii was not used. the leds are blinking. in bluetooth manager I can see it as Connected. then I try to run wiiuseexamle and it is not detected.
then I use dolphin and it can detect wii and I see only one led is lighting.
then I close dolphin and try again wiiuseexample. this time it works.

so the probem is to get it detected first time after pairing.
i hope now I explained better.
regards.

**Comment by janoc** [comment]
Sorry, no idea. I have never heard about this problem. 

That looks like your Wiimote needs some particular initialization or something (is it a genuine Nintendo one or a clone? Which model?) that Dolphin does and Wiiuse doesn't. You can try to debug it and see what is going on.

**Comment by gb2111** [comment]
I have 2 genuine wiimotes. one with plus included.
i was testing it on 2 machines and have same result. once I have first connection with dolphin, it works. but before that I just get info like nothing is connected.
if there is anything I can try please let me know.

**Comment by janoc** [comment]
OK, I have managed to install Wiiuse on a Windows 10 machine and test the current master from git. Wiiuse works without issues, but there are some typical Windows Bluetooth bugs because Microsoft hast changed how things work again. 

- Press the red sync button in the battery compartment. Do not use the trick with pressing 1+2 together anymore - that doesn't work on the last generation Wiimotes (the ones with the -TR name suffix) anymore. The Wiimote will wake up but will not let you connect.
- Add Wiimote using "Join Personal Area Network"
- When Windows detects the Wiimote and asks for a code, click CANCEL. **Do not enter any code**! No 0000, no 1234, nothing. The reason for that is that pairing Wiimote requires entering the Bluetooth address of the Wiimote backwards, which may not be possible if it contains bytes which are not valid characters the form will accept. Cancelling the dialog will stop the pairing but keep the Wiimote connected. This may fail, if it does, keep trying until you get the Wiimote showing as a game controller in your list of peripherals. 
- Once you have the Wiimote connected, you can start the Wiiuse example and it will work. 
- Reconnecting the Wiimote may require deleting it from the list and repeating the procedure.

If you want to avoid yourself this hassle, either use this type of utility (not tested): 
https://github.com/jmandawg/wiipair 

Or get yourself the Myflash Dolphin sensor bar:
https://www.amazon.com/gp/offer-listing/B00HZWEB74

The Dolphin bar is by far the easiest way how to get Wiimotes working with Windows. It acts as a Bluetooth host and handles all the connection business for you. Windows sees the connected Wiimotes either as a keyboard, mouse or gamepad, depending on the mode. The last mode is pass-through, where the bar handles the connection but feeds the data to Windows, so something like Wiiuse or Dolphin will work with it with no issues.

If you are planning on using Wiimotes in Windows, the Dolphin bar is the most reliable and simplest solution to all these issues, by far.
