### ISSUE TITLE
No wiimotes found on Windows; times out instantly

### ISSUE THREAD

**Issue by Masterchef365** [wiiuse/wiiuse#112]
On Windows 10, both the example code and any bindings I use to WiiUse fail to find any devices instantly, without waiting for timeout and without reporting any errors. On the same hardware under Linux, WiiUse works without issue and is able to read data from my balance board (this experiment was performed on two different machines and with both OSs). Attempting to set an alternate bluetooth stack through `wiiuse_set_bluetooth_stack()` has no effect, nor does changing the timeout duration passed to `wiiuse_find()`. I'm rather unfamiliar with Windows bluetooth development; where can I begin to debug this? Thanks!

WiiUse revision used: `dfbe3d2cd21d3d88d7ba9de39cfc8aa901a6041b`

**Comment by Masterchef365** [comment]
Found that https://github.com/jmandawg/wiipair worked for me, once I was able to pair with the device everything worked as expected!

**Comment by janoc** [comment]
In Windows you need to make sure the Wiimote/Board/whatever is **connected** before you start the Wiiuse application. One way to do it is as you have done by pairing the Wiimote and letting it connect to the PC automatically. Another option that works with the older Wiimotes (the pre -TR ones) is to delete any Wiimotes from the list of devices, put the Wiimote into discoverable mode (press 1+2 or the red button in the battery compartment) and have Windows find and connect to it.  Then Wiiuse will work. 

In Linux it is different because there the application is actually starting a Bluetooth search and connects by itself to whatever it finds. In Windows it only looks for already connected devices due to the limitations of the API.
