### ISSUE TITLE
trouble in using SDK10

### ISSUE THREAD

**Issue by Rakli17** [wiiuse/wiiuse#114]
Hey 

I am trying to make use of the wiiuse library to move a robot but have trouble in compiling the library for windows SDK kit 10 any solutions. 

Problems is about the WINHID in the cmakelist file. i have managet to compile the solution to SDK 8.1 but then i cannot use the library in my other project that runs with the SDK version 10.

I sincirely hope that sombody can help asap as i have on it for 4 days now. 

I use visual studio 2019

**Comment by janoc** [comment]
Sorry but without further information it is not possible to help you. Which version are you compiling? Which error are you getting? 

I don't have the means to build this for Windows right now but from what I remember  about Windows SDK kit 10, there were multiple versions which differed in the paths to the libraries. So you may have to modify the CMakeLists.txt files to account for it.

If you have managed to compile the library with SDK 8.1 then it should work just fine in a project using SDK 10, assuming you are not trying to build an UWP application. Use the C version of the library, not C++, so that you have a defined ABI and it should work.

**Comment by janoc** [comment]
Based on 3c7601030cc88154c86ad1971f85e8b66f000acc , SDK 10 versions up to 10.0.17763.0 (inclusive) should be supported.

**Comment by Rakli17** [comment]
THNX, i finaly found out that i linked the wrong lib file in VS it works now. I am trying to acces the gyroscope just by using the example you have provided in the motion plus where it calculates the angle_rate_gyro is there a decent way to get out just the data from the gyro when i print ou
twm->exp.mp.orient.roll,
               wm->exp.mp.orient.pitch, wm->exp.mp.orient.yaw

they are just zero. 

thank you in advance 
ps. havent close the issue, caurse i dont know if your are able to give me a hint on my question.

**Comment by janoc** [comment]
You didn't follow the example code.

You should be using these fields:
wm->exp.mp.angle_rate_gyro.pitch,
wm->exp.mp.angle_rate_gyro.roll,
wm->exp.mp.angle_rate_gyro.yaw

The mp.orient.* fields are not used/implemented. So if you want to get the current orientation angle and not just rotation rate, you will need to integrate that yourself over time. Wiiuse doesn't do that because it isn't really useful - most often you will need/want to use accelerometer, gyro and the sensor bar in concert to get a stable orientation (e.g. using a Kalman filter or something like the Madgwick's filter). 

Doing it from the gyro alone would both drift pretty badly and also impose regular updates so that the changes can be integrated over time. Wiiuse architecture isn't well suited for such design, it is better left to the user of the library to implement that.

**Comment by Rakli17** [comment]
thank you for that answer
