### ISSUE TITLE
gen20 remote doesn't get connected properly most of the time

### ISSUE THREAD

**Issue by PureTryOut** [wiiuse/wiiuse#121]
At first on the PC side it seems as if everything is alright as both WiiUse and my Bluetooth applet (on a Linux system) says it's connected but the controller just stopped flashing and indicates it isn't connected to anything.

```
wiiuse v0.15.5 loaded.
  De-facto official fork at http://github.com/wiiuse/wiiuse
  Original By: Michael Laforest <thepara[at]gmail{dot}com> <https://sourceforge.net/projects/wiiuse/>
[INFO] Found 1 bluetooth device(s).
[INFO] Found wiimote (type:  (motion plus inside)) (B8:AE:6E:31:79:3E) [id 1].
[INFO] Connected to wiimote [id 1].
```

After a few seconds WiiUse seems to realize it isn't connected and then starts printing out _a lot_ of errors:
```
[ERROR] Receiving wiimote data (id 1).
Error Details: Bad file descriptor
```

Strangely enough I did manage to connect it successfully once, but I haven't been able to reproduce it.
Since Bluez seems to think the device is still connected, this might be a Bluetooth driver/Bluez issue?

**Comment by janoc** [comment]
That is very likely a Bluetooth issue. Check the system logs (dmesg) for any errors or Bluetooth reports. 

Bad file descriptor error means the OS has closed the connection behind the library's back - most likely because the device has disconnected or some communication error on the Bluetooth layer has occurred, forcing the connection down. You may want to try a different dongle too - sometimes they are buggy, especially the random $2 cheap AliExpress stuff.

**Comment by PureTryOut** [comment]
I was going to say "but it works fine with DolphinEmu!" but then I realized, I use that in combination with the DolphinBar. Ugh, damn Bluetooth technology, it sounds nice in theory but in practice implementations can fail big time.

Well I guess that makes #66 even more important then. :sweat_smile: 

Closing this as "buggy Bluetooth adapter" then. It isn't a $2 cheap AliExpress thing (I'll never buy anything from there if I can get it elsewhere), but it isn't an expensive one either.

**Comment by janoc** [comment]
It is not necessarily the dongle but basically when you get this error it means something has gone horribly wrong on the OS side and the connection has died for whatever reason. 

It could well be your Wiimote too, especially if it is a clone. It could be also caused by interference (dongles have often poor range and sensitivity because they have tiny antennas). It could be due to buggy firmware in the dongle. Or driver support for that dongle could be poor ...

**Comment by PureTryOut** [comment]
It's an official Wiimote, that I'm sure off. But you're listening all kinds of reasons that's not due to the library, so I closed the issue :wink: XWiimote didn't manage to connect to it either, it's fine.
