### ISSUE TITLE
Writing data to Wiimote flash

### ISSUE THREAD

**Issue by matteoturini** [wiiuse/wiiuse#133]
I know you can read data with wiiuse, but can you write data to a wiimote?

**Comment by janoc** [comment]
Yes? No? Depends?

What kind of data are we talking about?

**Comment by matteoturini** [comment]
Arbitrary data. I want to store gyroscope calibration and an ID on the wiimote.

**Comment by janoc** [comment]
There is an EEPROM on the Wiimote (not flash) that can be written into but you are doing that at your own risk because its content isn't completely documented/known. So you could stop the Wiimote from working with Wii and even brick the device completely. 

You can use `wiiuse_write_data()` for writing it.

That said, your usecase sounds a bit like an X-Y problem (https://en.wikipedia.org/wiki/XY_problem). 

The gyroscope offsets are pre-calibrated, the calibration information is stored with the Motion+ and cannot be rewritten (AFAIK).  Wiiuse uses this information already.  

If you are hoping to calibrate the drift out, then that's a futile effort, that cannot be done - that is how a gyro works. One has to use some sort of sensor fusion algorithm (e.g. using Kalman filter) combining the gyro with another sensor (e.g. the sensor bar or external magnetometer) to get rid of that.

Re storing an ID - each Wiimote has an unique ID already - the Bluetooth MAC address. Now this is only directly available in Linux, in Windows and MacOS one would need to do some more OS-specific "gymnastics" to gain access to it.

**Comment by matteoturini** [comment]
Calibration purely for a program I'm writing. Not actual gyro data. But since it's undocumented I'll look at what I can do to get the MAC address.

**Comment by janoc** [comment]
You may want to look at this documentation:
http://wiibrew.org/wiki/Wiimote 

It shows what is known about the EEPROM. The functionality to read/write data is the usual `wiiuse_write_data()`/`wiiuse_read_data()` from `wiiuse.h`.
