### ISSUE TITLE
Update & Adopt PyWiiUse?

### ISSUE THREAD

**Issue by hendursaga** [wiiuse/wiiuse#134]
I remember using [PyWiiUse](https://pypi.org/project/wiiuse/) years ago, probably for wiiuse 0.13 or even 0.12, and it worked somewhat well. The [example program](https://github.com/tswast/pywiiuse/blob/master/example.py) even works to this day! I had to use Python 2, however. Perhaps we could update it to work under Python 3 / modernize it in other ways, and adopt it under the wiiuse organization?

**Comment by janoc** [comment]
Hello. That is a completely separate project, with a different license (BSD). So we cannot "just adopt it". It would mean a fork unless its author wants to be involved. However, seeing that it hasn't been updated since 8 years ago, I am not very optimistic about it happening. 

Furthermore, concerning modernisation and updating it - patches and pull requests are certainly welcome but I don't have capacity to maintain and develop yet another project myself.  The same probably applies for @rpavlik. 

Also, apart from that code being completely Python 2 and not compatible with Python 3 (not a big deal), it loads wiiuse by directly importing the `wiiuse.so`! I didn't even know that was possible, it obviously treats it as binary Python module. 

That is a cute hack but uber fragile (Python makes certain assumptions about its modules and Wiiuse certainly doesn't follow those!) and messy (see the need to symlink the library, etc.). And almost certainly won't work with modern Python at all. There needs to be a wrapper written for the Wiiuse library using e.g. `ctypes` or `swig`. 

So that "update" means almost a complete rewrite, IMO.
