### ISSUE TITLE
Balance Board No Longer Recognized

### ISSUE THREAD

**Issue by hendursaga** [wiiuse/wiiuse#135]
I was able to get the example working literally just yesterday, and now, whenever I try to connect the Balance Board, it says it's a regular ol' Wiimote and refuses to read any pressure data, unless I press the power (?) button, in which case it returns this helpful log event:

```
--- EVENT [id 1] ---
A pressed
Weight: 0.000000 kg @ (-nan, -nan)
Interpolated weight: TL:0.000000  TR:0.000000  BL:0.000000  BR:0.000000
Raw: TL:0  TR:0  BL:0  BR:0
```

I'm using Debian Stable and WiiUse 0.15.5. I can get a regular ol' Wiimote to work, still.

Any ideas? Could I 'force' it to recognize a certain MAC as a Balance Board or something?

**Comment by janoc** [comment]
Hello, 

That sounds very strange. Is that some kind of third-party (clone) board? Or original Nintendo?

I don't think there is a way to override the detection, it works by reading the expansion identification whenever a new expansion (nunchuk, Motion+, etc.) is detected. Balance board is basically a Wiimote with a hardwired special type of expansion.

From your description my guess is that you have a board that is "butchering" the protocol somehow (3rdparty devices are well known for that) and that confuses Wiiuse. 

You could try to compile Wiiuse from source and then modify the function `handshake_expansion()` in `events.c`. That function is a state machine that tries to initialize any connected expansions, get their ID and the do the expansion-specific init. 

However, I suspect that in your case the problem is more that the internal expansion is not being detected at all because the hardware isn't sending the correct packet telling Wiiuse that there is something attached. 

If you compile Wiiuse in DEBUG configuration (`-DCMAKE_BUILD_TYPE=Debug` or select Debug configuration in Visual Studio, depending on which compiler/IDE/platform are you on), then it will print out complete dump of the communication. Try to capture and post that here - from the connection until it starts to print some reports. Without seeing what is the board actually transmitting I can't really help you.

**Comment by hendursaga** [comment]
This is an original Nintendo product, yes. Furthermore, it's rather old, so yes, it could be a hardware problem. It might be that the batteries are too low - at any rate, I'm going to have to wait for some more to get recharged, as even the power button doesn't respond. Are you aware of low batteries interfering with the protocol?

Once I get some charged batteries, I'll try and connect it to my Wii console and see if that works. If it doesn't, then I'll try and take a look at the physical hardware. If it does work, I'll try again on my computer, and if that doesn't work, I'll see if I can get a BT dump..

**Comment by janoc** [comment]
If it is original Nintendo, then it should work. 

If the power button isn't working then there is certainly a hw problem of some kind. 

>Are you aware of low batteries interfering with the protocol ...

You mean like a dead battery causing the device to shut down mid-transmit? 

That's a basic thing - if something is battery powered and is malfunctioning, check the batteries first! And try with fresh ones. I would even suggest testing using normal alkaline batteries because rechargeables have a lower voltage and Wiimotes will show them as partially discharged even when freshly off the charger. They should still work for normal use but the point is to eliminate as many known sources of problems as possible when debugging something.

Low batteries can cause all kinds of strange issues with the device not outright dead but malfunctioning in various ways.

**Comment by hendursaga** [comment]
I put in fresh, rechargeable batteries and it appears to be working now. Sorry for the noise!
