### ISSUE TITLE
CMake fails on Windows

### ISSUE THREAD

**Issue by AliceRixte** [wiiuse/wiiuse#139]
Hello, 

I've been trying to compile this library on windows, but it fails with the following message : 

```
CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
[cmake]   Could NOT find WinHID (missing: WINHID_LIBRARY WINHID_SETUPAPI_LIBRARY
[cmake]   WINHID_INCLUDE_DIR)
[cmake] Call Stack (most recent call first):
[cmake]   C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
[cmake]   cmake/FindWinHID.cmake:229 (find_package_handle_standard_args)
[cmake]   CMakeLists.txt:51 (find_package)
```

Is there a work around or a fix for this issue ?

Cheers !

**Comment by janoc** [comment]
There is no workaround, that's a hard dependency on WinHID, which is part of the Windows SDK. It used to be part of the Windows Driver Development Kit (DDK) in the past. You need to install that. 

It is looking for `setupapi.dll` and  `hidsdi.h` - if you have those files on your system you may have to modify the `cmake/FindWinHID.cmake` to find them. Different releases of the Windows SDK and Visual Studio like to place them in different places, so it is possible the existing list of places where CMake is looking for it needs to be extended.

Patches/PRs are welcome because I don't have a Windows development system.

**Comment by rpavlik** [comment]
I assume it's probably in the windows sdk these days.

**Comment by rpavlik** [comment]
yeah that's in the normal windows sdk now. I might be able to quick sync some cmake scripts to make it happen

**Comment by rpavlik** [comment]
Hmm. It worked fine for me without any changes, in all the configs I could try:

- Generating for Ninja, from a developer powershell
- Generating a VS2022 project using the cmake gui
- Generating by "Open Folder" in VS2022

So I suspect you're missing some stuff in your visual studio or something. When in doubt delete the generated build dir.

**Comment by janoc** [comment]
I also recall that this used to work without having to do anything special as long as one had normal MSVC C++ development tools installed. However, I also remember that the different revisions of the Windows SDK/platform SDK liked to change the locations so maybe it got broken again in a recent version. 

Good to know it still works fine.

**Comment by autonym8** [comment]
Thanks for the answer, I haven't had the time to try it out yet, I'll come back to you as soon as I do :-)

**Comment by janoc** [comment]
Yes, please check if it builds for you and close the issue if it does.

**Comment by ace4971** [comment]
works for me, and yeah it seems to be part of the windows 10 SDK (and probably 11 too)
