### ISSUE TITLE
Pitch and Roll change together

### ISSUE THREAD

**Issue by varadig** [wiiuse/wiiuse#62]
Hi, when I connect the wiimote, and pitch, the value is changing, but near to -70 is the roll is also changing. What I'm missing?

**Comment by janoc** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 27/07/15 13:45, varadig wrote:
> Hi, when I connect the wiimote, and pitch, the value is changing,
> but near to -70 is the roll is also changing. What I'm missing?

That is normal behaviour. If you are using only straight Wiimote, it
uses the accelerometer for getting pitch and roll by calculating
arctangent between x and z axis (for pitch) and y and z axis (for
roll) - i.e. nothing super sophisticated. See the file dynamics.c for
the code.

When you pitch the Wiimote to a -70 degrees or more, what is happening
is that the force (accelerometer measures force on a small moving
body) in the former "z" direction becomes small and you are dividing
by a tiny number, causing numerical instability. Basically a tiny
change, even due to a noise, produces large change in the result. So
you get spurious roll.

The other problem which happens is a gimbal lock, whenever some of the
angles is close to 90 degrees. The accelerometer itself will actually
report those incorrect roll values (or rather the data that gets
converted to the bogus roll value). If you are near +-90 degrees
pitch, then roll essentially becomes yaw and it is not well defined
any more.

There are ways to avoid this, but it takes a much more complicated
code. If you want a robust solution, you will need to use the raw
values from the accelerometer and track the angles yourself. Once you
get close to 90 degrees on some axis, you will need to swap the axes
from which you are calculating the angles (and compensate
correspondingly), so that you avoid that division by zero singularity.

The ideal solution is to not use Euler angles (pitch/roll/yaw) but to
switch to quaternions which don't have the gimbal lock problem. Also
you could use the Motion+ gyroscope and fuse the data with the
accelerometer instead - e.g. using a complementary or Kalman filter.
That will give you a much more robust solution and will allow you to
track also yaw - something that an accelerometer alone cannot give you.

Regards,

Jan
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iD8DBQFVtpHDn11XseNj94gRAn6tAJsEONBwwK4icKtDl7ziCgdwg5wXPgCdH5fu
7ubdEleKtP91Yk9o2vDlM8c=
=M6HS
-----END PGP SIGNATURE-----
