### ISSUE TITLE
Orient gforce data is lag

### ISSUE THREAD

**Issue by jeok70** [wiiuse/wiiuse#71]
I'm enable motionsessing, get old data

Why?

**Comment by janoc** [comment]
What do you mean by "old" data?

Without knowing more about what exactly you are attempting to do it is difficult to help you. I have certainly not seen significant "lag" or old data with Wiiuse before. Could you be a bit more specific, please?

**Comment by jeok70** [comment]
I'm use Python time.sleep() test lag , so that data Occasionally information before translation

**Comment by janoc** [comment]
Uh, so you use some sort of Python binding for this library and not the C/C++ code directly?

Does the lag happen with the examples that are shipped with Wiiuse too? Because if it doesn't, the problem is somewhere on the Python side and there I cannot really help you. 

However, keep in mind that Wiiuse is not using threads internally, so if you aren't calling wiiuse_poll() frequently, no Wiimote data processing is done. If you are using time.sleep() in your code, that is most likely why you have that "lag" - the data is processed through the Bluetooth sockets on the first come first serve basis, so the accumulated old data has to be processed first before you get fresh data. This sounds very much like a programming error in your code to me.

**Comment by jeok70** [comment]
My code is that url 
https://gist.github.com/jeok70/27b027f5022c19a55de5
The problem is repeat wiiuse_poll?

**Comment by jeok70** [comment]
https://gist.github.com/jeok70/11b7c048155944d83553
that url is Python wiiuse libary

**Comment by janoc** [comment]
No, your problem is that time.sleep(2) there - you are sleeping for 2 seconds on every iteration and you are surprised to have lag??

Why did you put that sleep there in the first place? If you want to have a decent update rate you must call the wiiuse_poll() like 20-30x per second.

**Comment by janoc** [comment]
I haven't gone through all your code, but there also few other big red flags.

- your calculation of elapsed time is wrong, because you are calling time.time() twice, so there different times used in the elapsed time calculation and stored for the next iteration

- you are trying to calculate rotation rates by numerical differentiation, for ex.
  self.roll_velocity = (self.roll2 - self.roll) / self.time2 

This will give you big errors, because if self.time2 is small, you are dividing by tiny numbers, so any noise that is present in the data will be amplified. I do wonder what do you actually need this for? 

Moreover, if you need the rotation rates for something, you can take them directly from the Motion+ gyroscope of your Wiimote - that is what a gyro is made for. The raw data are available from Wiiuse.
