### ISSUE TITLE
CMAKE error on Windows 10

### ISSUE THREAD

**Issue by usernamevalis** [wiiuse/wiiuse#73]
Im getting an error where CMAKE is not finding the WINHID libraries

`CMake Error at E:/Applications/cMake3.3/CMake/share/cmake-3.3/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find WinHID (missing: WINHID_LIBRARY WINHID_INCLUDE_DIR)
Call Stack (most recent call first):
  E:/Applications/cMake3.3/CMake/share/cmake-3.3/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindWinHID.cmake:123 (find_package_handle_standard_args)
  CMakeLists.txt:53 (find_package)`

I've installed the driver development kit but cannot find the correct lib's (libhid.lib, hidsdi.h, inc/crt/stdio.h). Im new to windows so im not sure if I've done something incorrect or if the W10 WDK uses different names for these files. Any help is greatly appreciated.

**Comment by rpavlik** [comment]
It's possible I need to update the CMake modules in this project from my main CMake modules project, which does find the windows driver kit. I don't recall if I updated the win hid module accordingly but I think it uses those underlying modules to help.

**Comment by usernamevalis** [comment]
Could you possibly tell me how to do that? 
And also where the files would be on windows 10, or what they are called?

I've installed the wdk but I cant find those files anywhere on my computer.
Thanks

**Comment by kosenhitatchi** [comment]
Good afternoon.
I'm also having the same problem here.
I'm working on windows 10, use the [associated WDK ](https://msdn.microsoft.com/en-us/windows/hardware/hh852365.aspx) with CMakeand visual Studio Express C++ 2010.

Even If I manage to generate the solution, I cannot link properly to the WINHID libraries.

Could you tell me (even if the CMake modules is not up to date), which path should I use in CMake for :
**
- WINHID_CRT_INCLUDE_DIR = ?
- WINHID_INCLUDE_DIR = ?
- WINHID_LIBRARY = ?
- WINHID_ROOT_DIR = ?**

I tried : 
_WINHID_CRT_INCLUDE_DIR = C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\km\crt
WINHID_INCLUDE_DIR = C:\Program Files (x86)\Windows Kits\10\Include
WINHID_LIBRARY = C:/Program Files (x86)/Windows Kits/10/Lib/10.0.10586.0/um/arm64/hid.lib
WINHID_ROOT_DIR = C:/Program Files (x86)/Windows Kits/10_

But I still cannot compile Wiiuse with this.

Could you give me an hint. Otherwise I'll switch to a win7 machine to compile wiiuse.

Sincerely

**Comment by janoc** [comment]
Please test my version from here: https://github.com/janoc/wiiuse 
If it works, we may merge it.

@rpavlik Could you have a look at my CMake-fu, please? I had to manhandle your script a bit.

**Comment by rpavlik** [comment]
Should be made unnecessary by #77.

**Comment by janoc** [comment]
Cool, will check it tomorrow.

**Comment by cdekkers** [comment]
Although I read that the above issue might be solved, it still occurs on my machine. I have the Windows Driver Kit - Windows 10.0.15063.0 installed, and CMake is still giving me the error `Could NOT find WinHID (missing: WINHID_LIBRARY)`. What can I do?

**Comment by cdekkers** [comment]
> @cdekkers Is this still a problem? The current Wiiuse compiles fine for me on Win10.

I think I moved away from the wiiuse library in the end, because I wasn't able to solve this issue. Considering this occurred one and a half years ago, I do not remember the details. Might have been a problem on my end.

**Comment by janoc** [comment]
OK, no problem. Then I will close this.
